### ISSUE TITLE
Queries on False Positive on Benchmark test 

### ISSUE THREAD

**Issue by tiru1930** [sonos/nlu-benchmark#4]
Hi 

I am referencing the https://www.slideshare.net/KonstantinSavenkov/nlu-intent-detection-benchmark-by-intento-august-2017 , in this slide share on side has accuracy for False Positive.

I didn't understand correctly how You came across to that figure. Can you please explain how  this test has done? and also What is the data set used for this False positive test. It has mentioned that NLU 2016 samples are used for False positive , Though intent names are different in NLU 2016 , some of the quires are matching with quires in NLU 2017,which we have used for training. So I am bit confused on this. Can you explain the same and also please provide link for the data set used for this test if  it is publicly available.

**Comment by JDureau** [comment]
Hi,
The benchmark you're pointing to was done by Intento. We don't have access to the underlying data, not have much details on the methodology.
Best,
Joseph

**Comment by tiru1930** [comment]
Thank you
