### ISSUE TITLE
Wrong 2018 chatbot results

### ISSUE THREAD

**Issue by jesus-seijas-sp** [sonos/nlu-benchmark#8]
Hello, the chatbot results located at https://github.com/snipsco/nlu-benchmark/blob/master/2018-01-Braum-et-al-extension/results/chatbot/snips_metrics.json are wrong, because this file includes the testing against the training data. Test data for DepartureTime intent is 35 sentences and the result contains 80, and FindConnection should be 71 total sentences, and the result contains 130.

**Comment by adrienball** [comment]
Hi @jesus-seijas-sp,
At the time when we ran the benchmarks, the chatbot corpus did not contain any training flag. I just had a look and this information was indeed added [2 months ago](https://github.com/sebischair/NLU-Evaluation-Corpora/commit/887433e280314bea92bbc971a96cd81cc11be261).
As we did not have the train-test split for this corpus, we ran a 5-fold cross-validation. 

I will add a note on the README about that, thanks for reporting.
Best,
Adrien
